  version: 2.1
  jobs:
    BUILD_A:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command
        - run: 
          command: |- 
            mkdir 201911111515
            cd 201911111515
            touch a
            touch b
            touch c
            ls
        - run: 
          command: |- 
            ls    
    BUILD_B:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    BUILD_C:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    acceptance_test_3:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command     
    acceptance_test_4:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    deploy:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command   
    PUBLISH_A:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    PUBLISH_B:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    PUBLISH_C:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    PUBLISH_D:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command          
  workflows:
    version: 2
    AAAAAA:
      jobs:
        - BUILD_A
        - BUILD_B
        - BUILD_C
        - acceptance_test_3
        - acceptance_test_4:
            requires:
              - BUILD_A
              - BUILD_C
        - deploy:
            requires:
              - acceptance_test_3
              - BUILD_B
        - PUBLISH_B:
            requires:
              - acceptance_test_4
        - PUBLISH_A:
            requires:
              - acceptance_test_4   
              - BUILD_A 
              - BUILD_C    
              - PUBLISH_D      
        - PUBLISH_C:
            requires:
              - deploy
        - PUBLISH_D:
            requires:
              - deploy                            